apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: bob
  namespace: crossplane
spec:
  forProvider:
    enabled: true
    email: bob@domain.com
    firstName: Bob
    lastName: Bobson
    username: bob
    realmIdRef:
      name: home
  providerConfigRef:
    name: home
