apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: x.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: kube-prometheus-stack
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-values
