apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      version: 24.x
      sourceRef:
        kind: HelmRepository
        name: keycloak
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: keycloak
  valuesFrom:
  - kind: ConfigMap
    name: keycloak-values
