---
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-installation-scripts
data:
  install-apps.sh: |
    #!/bin/sh
    echo "Installing Nextcloud apps..."
    php /var/www/html/occ app:install user_oidc
    php /var/www/html/occ app:install notes
    php /var/www/html/occ app:install bookmarks
    php /var/www/html/occ app:install deck
    php /var/www/html/occ app:install news
    php /var/www/html/occ app:install groupfolders
    php /var/www/html/occ config:app:set --value false firstrunwizard wizard_enabled
    php /var/www/html/occ app:install side_menu
    php /var/www/html/occ config:system:set maintenance_window_start --type=integer --value=1
    php /var/www/html/occ db:add-missing-indices
    php /var/www/html/occ maintenance:repair --include-expensive
    php /var/www/html/occ user_oidc:provider keycloak --clientid="nextcloud" \
    --clientsecret="j2ecUssTHhdIyz1HVZDZcdWP1fHxtuz5" --discoveryuri="https://login.thecullensnz.com/openid-configuration"
    echo "Nextcloud apps installation complete."
