apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  #- namespace.yaml
  #- repository.yaml
  - sealed-secret-nextcloud-admin.yaml
  - sealed-secret-nextcloud-database.yaml
  - helmrelease-nextcloud.yaml
  - traefik-middleware.yaml
configMapGenerator:
  - name: nextcloud-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
