---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-admin
  namespace: nextcloud
spec:
  encryptedData:
    password: AgBDB7vXbNn1Yyw4vo7oWFjFkMIja4m2WM6Eiou2q3G+DiZCy2YG+0ERZ6bWK5CdKvTkwl+8wL6dNz5BNIA5OgUN+DTQFfN9Ml6x1ElJz0jbxpcGJSY+g7A5Akb62+Ujh1aACnFh/q+u/atSe8YtQ7t31YrgdHSBYG9uFolCIr0ZppLrusr+N0uy6WEfTvGNqhAUczyWxkQsehxvaDmHwsxdAWQ+NSCeEUKD12ZyXfJZ3VM02jZFbFk2Y0kpNQOtE/CKnOy8C9y8XE18glcwhAdXCbQFXUJIEGGhjZanhDcsAZlT3/AH+RkpJuHg95+x3AXTqzXOKt0NP89XL6aD4YKqJOpJ8s0WeE3IovKwt4lyMyCOeSagwrtGd1eLS/O1ks7vZZI8JpYScu3K+LLt7b54boGonIvakxx8DZeH0QRYlYIaxkCHDlBSxegAWaUsaIF8phHsypMo3vts38SwrbErdG64pZE2AAMKr9gJOyUW46TJSrxE777g/8IilZ6XXQaYn2hGgQbxQmVL5yuAHfC6ka5iaYuOLTuY1qPPp3iS2gjpGH/YGqhMo9fZ9CnPlrW0WkKQkRWWYtKnyNlML5XTV6jyXQjhGy2KBH73Le2sXtibS9VE9L2ThO/jo3Ju+CQTD0sS+SNY5wlrDAONBOQZQ39/qSDat0efCLf4j6X0E/AtSot+4xakN1vNMzI9ZGhqU3VDafnwItb7ySE=
    user: AgCNbELDaz7s1b4V9+qkgWH6bFUkg/oEloRA4RdyqWaaobvoT0PX4RoR2QmELfz7C2B7peBwNBU0F7kisuY8OIz4bJZpJNvu9LCbL6YvSgPZE20R9kl0+dmtpmYCRZmPWZbV0rbqE235RGkUbNc6lblH4VxwM9/t4qXnye5IwRUbvdtjbBY8QHRDyP5RgBc8TdVKUOSZigDZ817g1RGL7VQFjzaNt+OoHxrk/SvVkjcP4nLryjThlJdMsVauu4hvhqTiB3prAPQ8S6ID7w5o4KG7UC3mGyFCxjF9EZ4sV1+i1Zya3OySWHnu2PdTPYr3yERokalbNa4khIBcQo/sLyNJT8M+3AtnV7QWgPJ12hjRBMPRBHSzw8fSvAk+aFK0fkqhM2biD88Xy4zEuCPUKNDNFPFgKvj+1k5NPFQI8xoFGoxNoHg/vs8hppzTgoRabWSOcS+zgR8VBxxHUJqfKTldAZyvBfGWGY5QJxS7PBbhH+bgJGDpxL9RD45vRjcmRF4+Fle7JjjTV749PuiCtl1NVUdBlVtfdbn1VhuM64It7QL1QGEwoPHImPx9mE1PAyOVyIhDdCNFnhAMPlGRC3aBXCZ1Q7wV1joUb4wImASRDV3GL2QE3zr/CUPk6OoACuynAfHawcmBb9wuIqeoqA7LtWaKdunGqqnFfNq4v5joErV/xjZ4ejHjJv9WxApuzGRTzmX1nQ==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-admin
      namespace: nextcloud
