---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: nextcloud
spec:
  encryptedData:
    password: AgB+KwC9sBBtgsC5ZfMzLIIVSJWsbL8crLoUwppm9dD5zfOHxyGPcd32IQV7WCwFljOP6N4q6cSgf9Y0u22f0SyZsQZVEfQoIOchjTpKTP4sVGQviyrRF+E0ftPsybeyZ8/x/ahxkGvVg8kpU4Ylb0U9x6pn5iuAEoKGgQ4tOIODTH0dwfZIl+rYrOAKxwYE/e+pRyoOXfLuURgHHdKz9wVKeOEc12U+1WKSX5Azu8vXRfFcoy24tfPlc5gA/Pm1n6dOXHf597S5znn5QFPWDwd4QS/2imml4UGp9y73D6kMkBA5N3/fdhxdXLZNIZFFjJusUM0IyawgRThnqY6DdS1nD+GHNIFO96O+zCm2g7n6YEMLOfCWuH4qZLc/u5cf0tHjrQ0KKK9WpJ3/ThAp/3f0kDAfDjHxHLQUggH2C5ffCY+93P/sTQ/D+GFoJkCk7+iwatYh9TXRwbUIawO3Pp8KqlxcoZoYNfsYB+NIUhJOdOxqMHzVKW2avlv51qH2d7okQ6L0Fd/zvly3I7YOYo9x3rnaeSqSlBjJJjwYi3bsWmogJOV24IbnagqXpR/4Px3eJsQHgT7eYy/TXkF/pHoA4/qbI8/LAyaWBsvnVedy7BdoIjhAtpkwgKi1aL/XXTotFhTo36IBvHFrdLoN/CFn526dYGC78fptUhqq7/eo/V2ACMV5/4+8VOH1o2uekDIMilz4psqD8OtFMOM=
    user: AgCeiULsjJ/8nl8NEmKdzUkNmSLnsla3gK4pOyQLfcwfvrH5iVHTkPa6mRgDCfM2UBT2K781EW+jku0CqJMVgJhcS/l6P+7+O+zgKnwxJstRmBzzPCLtd/K2hJTR5pO63vuXsqLZyfAZedCy9tEhVHfHcBeTOILllwz2GMOmwh+0+PWuNThqrdK14dUpeAoAkmmCtNDgILZfk9Y21hIK7QE0hQ0dvX9kXU5aRhIHNWsaMlm0yNEoSg5BJFyi3pfhuxi5DPIiNKFxPzroS9NtToQ+/jp1cR12nxkb0oACPRV2VaxCSXXEvyNO45UgEAd+v5z6JSLReLSUt1TceWcbFd5L33EAU8vpjn+5Jk+Zk5mA9fDSOdj1RSFFYvVvx0Y2gLYD3WyHNPMAIZ33HCFKmDpOubUmlOL7rnzoj94eNlKZUiWROluuBnn1Zup2hbOC3JQ6UpMXlFHX2WDiJTxCKHrzuO09RJ28XjRBS5C11SDxRXpPslEo2h76TXupunrLGbWb4KzXek2v3gWWDkOjasxv7IBA1DKoyJGPDUjktnUjLm09OQ5jHnf3V2k/h+ki1F1FIhKWzp4w9yR8Ok1K3WDNh9RPMabAxzd6ueKfdhM42EkOH9v/pY2TylUK+lJabD3BpSgG+q4CN3YP2JljZnfZ5l2QexW497O4uU5LiRtwgCpIR4eRHn28Hrt0G8oid6n35AFMhg==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: nextcloud
