---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-admin
  namespace: nextcloud
spec:
  encryptedData:
    password: AgCn/L2lUyNkiAb8DDFYWptgRYRIvLY23gjd7m3IMUYLfMUZs8g13tgmlqJ1CyPByQSEZhlp2IelYTy0/tfl6r0vXyFnR/96X/MlJCQSVrhsJqRZzOIU2gvcsWJjbMYmPJ3h8fqfSEU9oNHtzvCZV5OTrPNqzi9YLDdMOAh7kCtGuaeDIwsTF5AztrcJAEFOWdKs9CbYwIb0yCadMwm4qT0cIkDxDvpoN+rrtTRys8RqA5MiifaDULyGhn5mMqay21etbxgb/zuXjT5V6SyfhTD0XWcYwsXkB/fgAaJb2oKEcwOlnfy/k4gAsTVLCo9LWt7+Lre87HlQLbr+kxxOuiBEkVV9yzbW65SocbAhNRqTrZ3FTe0w1l3jLcdfPVd27cqdPwZucSUJbd6snn9K9KXIXX4KVRBV27nVG6oCFcNumdqhVTjmUvNgz4SsBaRaWf+y5VGs+whn9FtNObhaHa+zy20lYRONyQMmQFpB6bMk97s2QNufdbzWpotYpHKxeLKnlyyb19marmjuuu8B/xggAIE1dX7DK/xo/6TGI16kt6jP9OWkvCJqVy+KQnBcnwy5lPIr+1XUWkllgCsFGYs/0AUi9SLVZSRlCEtXzEA1LWwxbsHtrky03a/Joesg/j4fZlVg/XRwdVQm0bazR/wdsYcL49580nd/1wY0NQPqKtwbYK9+k+2Hmad0hxKMTq1e9+jErIDQoxqrUNo=
    user: AgBkQMBvmtVboNeY9LQvUeztMeKPCBSeo03yxkOrC2+7siVrOsYBtL35BIz1KunyaRyKSA8pBTqNjdyz7qfZRjqQLi0xYdmlWUcgVWb+3G8lKQzNvQYmJoKjn5b7XPJqV5lbyIHQjEPclgtgU1R3brtv5wGBYL1fao2TtJvEOwgodqD+tqEKCyk6mnqfPjvV7mX7hoLRuA/JK8Imo/9Q/Gj/+E3H4ynqP9TdRzeu34Xd4IkGTtgeVoQPzrul+Rww0EfNIYMtlmPhgHgAzTB3FT0bCD6rFbtzKZHG86kuo/G9fwTGRZDl6TrucZ3kPgPCTBG6KHDqoiMOWllaAdz8P0/JUzgu75nmdHOplYKWkiiPt0Qe1/XZmfb8cjakxKvn0MlqY9cyTrRbDtrV677+sd4tXftG4C2ClGH+P7aMIfoRrpUAJs1FMJXIG4OtxALZJ74nrFwX764D+34JBwcqvhh1gkiFBlUC7G4ll3B5ldvDv7XAxhsyTq+hn/kzP53NY5wGcd3czccZmB6n4Ao4EvS+SP6JpDiOWi5/75/oMC6TdY1sNqSLynShDj+VtOnHVDn/0oG0K68kqO/OS5TqNa0WMVgzl8rwGhqA+CBoiXpKqZw42K+h+HnVENNfxPFsdhZ/+ITwptqsKc5HhepdZLq1v58THjToFOD9oASFWMiEt3UOz14p6g6NI2EOpHamXEFQHdbMfQ==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-admin
      namespace: nextcloud
