---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-login
  namespace: nextcloud
spec:
  encryptedData:
    nextcloud-password: AgBvo0Dm8R0dEfU9rg2KRC15u1eLBLwnNNzVxHaq3j83XY60CqGWh52K8D2LSt/NvkuGJZZD2YkrsNq6j9x1luIrU2AaEqhlK2YVCRj3iRmfQuJ9oA8yKNx1Ak0K+IEfpg/Yq+A59YWrapNpWVkaesnlIECqMcQEtXuykJzWH21nDwwk6coKvAqeqZp05HSOQKyq4QwTCYbWYt+Tc2hbCuk+h+By+SOiDL4rYBBnblS+HSVm23JXX2S3lEIZJXPawtSwEvATZ63RpdZFMbeq3/SBN7DCrTH8keexEEdunpwdskGWzFdPWNzklMxseBFZRsT5NCBcw6QI4eNrdiircsq3ioIRGM68vUKuOvJHTXmVoI6/v7ae3DH9c62H3gVgDOgZRBY+PhjQPwlJCO1iRHyImhHXv5AwquUeHJKCY60L1va0XYPY5rFASPr1uI8Xa6cdgW09hvOcZ5ZMpNrE6xr6nef3Bp1+Ta8jcz5XUtTkNXjTXK0NxBdK95oqWwYpbi6kTQpjhQFsybTh1hlCYOl6PSL7MK7b+Gnh90JBIJw4kwguS1EB/+5wi00cLSm8nH9SPLCKWBG87MdTuGpl5vrx1gxoIWGb6YF0+GkFrP9LNBbveI14PkVK28UB8bsQJvp09LPtxG57GRpVBqtzvQb6aC2ZvGWleEzFgNh46LoVjzlEH3BPlEnTi+W8KMCZsoc4Fw//BJzJ4/eQEAs=
    nextcloud-username: AgBSKuLhC2eOQQ9zcueP26vgrC7drFSPJjB9/DHtRCGrcnQlWfGqLgm4S2rxV6weNe3D/Nbnk1HS+0oCORw68tHSj6pKBbMEZsGZUPS6sfaht+qlx7AKX0x2N9TgRPXiUsnPFHvW3KNU7RvnxYvrRpkH7mbdR9oGgv+nbJ5PfP+LlfiSH3CsSEV9Iw32JjOtBaocVI8gVoUTDz7lHjYjP+33LH68bESc63lSBzi+Lp2Rttikk/E3p+x3vUOlPDo2kLpWSfL2mURXshkAxJ4qXP86Im7TWDCCgCf8nKKjrtchcjm2By+2Scd54QWMLvvjikQWF8qz8uC6v4CdbzfIITQStkAUi9V+PhtDmaLAR2QatymG8qvgCh50uM9FTFOjdDUWrZr+81LBoi8HU1+mAi+mOghFRSFfCPrOEwygz4Ko71UAQ8O66I/s9iuhgjmNH0Q11bHA8z7xAbqBu02yTDco+TiwlpZfMQ5OZGZL3BM5Fnx7BAhOM6hlugJZPwEjIrXtmz3p8kYs5TRCIZmYBimPzRMkuAcIu0I2b840xpJwToPTHp3XXuPojr80dbTo4y5E/yjQ/Rk5guBqL2zgg2yCYdff0aA7jL/LQ39S5mxRCp0Tcr6XgncWfcPYp7pPm4cHFCF0atrs2FSBZW7ePxPuFYNWdIqiUpgymrOd4gGrGTQ/H/6mwoEdys/uZnNi+ozgfmcOtQ==
  template:
    metadata:
      creationTimestamp: null
      name: nextcloud-login
      namespace: nextcloud
