ingress:
  enabled: true

nextcloud:
  host: files.thecullensnz.com

image:
  tag: 31.0.1-fpm-alpine

nginx:
  enabled: true

postgresql:
  enabled: true
  architecture: standalone
  global:
    postgresql:
      auth:
        password: "testing123456"
  primary:
    persistence:
      enabled: true

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  password: "testing123456"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

cronjob:
  enabled: true

persistence:
  enabled: true
