ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-middleware-headers@kubernetescrd,nextcloud-nextcloud-middleware-regex@kubernetescrd

nextcloud:
  host: files.thecullensnz.com
  existingSecret:
    enabled: true
    secretName: nextcloud-login
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
  extraEnv:
    - name: OVERWRITEPROTOCOL
      value: https
    - name: OVERWRITEHOST
      value: files.thecullensnz.com
    - name: overwrite.cli.url
      value: https://files.thecullensnz.com
    # This is the Cluster Ip of the loadbalancer
    - name: TRUSTED_PROXIES
      value: 10.42.0.109

lifecycle:
  postStartCommand: ["su", "-s", "/bin/sh", "www-data", "-c", "php occ app:enable user_oidc"]

image:
  repository: nextcloud
  tag: 31.0.2-fpm-alpine

nginx:
  enabled: true

postgresql:
  enabled: true
  architecture: standalone
  global:
    postgresql:
      auth:
      existingSecret: "nextcloud-database"
        # Names of keys in existing secret to use for PostgreSQL credentials
        secretKeys:
          adminPasswordKey: "database-admin-password"
          userPasswordKey: "database-user-password"
          replicationPasswordKey: "replication-password"
  primary:
    persistence:
      enabled: true

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  existingSecret:
    enabled: true
    secretName: "nextcloud-database"
    passwordKey: "database-user-password"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

cronjob:
  enabled: true

persistence:
  enabled: true
