ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-middleware-headers@kubernetescrd,nextcloud-nextcloud-middleware-regex@kubernetescrd

nextcloud:
  host: files.thecullensnz.com
  existingSecret:
    enabled: true
    secretName: nextcloud-login
    usernameKey: nextcloud-username
    passwordKey: nextcloud-password
  extraEnv:
    - name: OVERWRITEPROTOCOL
      value: https
    - name: OVERWRITEHOST
      value: files.thecullensnz.com
    - name: overwrite.cli.url
      value: https://files.thecullensnz.com
    # This is the Cluster Ip of the loadbalancer
    - name: TRUSTED_PROXIES
      value: 10.42.0.30
    - name: KEYCLOAK_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: nextcloud-oauth-client
          key: attribute.client_secret
  extraVolumes:
    - name: post-installation-scripts
      configMap:
        name: post-installation-scripts
        defaultMode: 0550
  extraVolumeMounts:
    - name: post-installation-scripts
      mountPath: /docker-entrypoint-hooks.d/post-installation

image:
  repository: nextcloud
  tag: 31.0.14-fpm-alpine

nginx:
  enabled: true
  config:
    # This generates the default nginx config as per the nextcloud documentation
    default: true
    headers:
      "Strict-Transport-Security": "max-age=15768000; includeSubDomains;"
      "Referrer-Policy": "no-referrer"
      "X-Content-Type-Options": "nosniff"
      "X-Download-Options": "noopen"
      "X-Frame-Options": "SAMEORIGIN"
      "X-Permitted-Cross-Domain-Policies": "none"
      "X-Robots-Tag": "noindex, nofollow"
      "X-XSS-Protection": "1; mode=block"
      "proxy_set_header": "X-Forwarded-Proto $scheme;"


postgresql:
  enabled: true
  architecture: standalone
  global:
    postgresql:
      auth:
        username: nextcloud
        existingSecret: "nextcloud-database"
        secretKeys:
          adminPasswordKey: "database-admin-password"
          userPasswordKey: "database-user-password"
          replicationPasswordKey: "replication-password"
  primary:
    persistence:
      enabled: true

internalDatabase:
  enabled: false

externalDatabase:
  enabled: true
  type: postgresql
  user: nextcloud
  existingSecret:
    enabled: true
    secretName: "nextcloud-database"
    usernameKey: "database-user"
    passwordKey: "database-user-password"

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

cronjob:
  enabled: true

persistence:
  enabled: true
